### ISSUE TITLE
Deadlock when loading robots in multiple environments

### ISSUE THREAD

**Issue by Konijnendijk** [xillio/xill-platform#8]
# Summary

When using two or more `XillEnvironment`/`XillProcessor` instances to load robots at the same time, a deadlock can occur. 

The deadlock occurs inside XText. Internally XText uses Guice for injection. When creating a singleton with guice, this uses locking internally. 

Somewhere in the dependency graph of `XTextResource` exists a `@Singleton` annotated class, causeing a lock when it is created at `XTextResourceFactory`:20 using a `Provider<XTextResource>`. Also during the creation of an `XTextResource`, internal resources are fetched using a `SynchronizedXTextResouceSet`.

Another thread simply uses the `XillResourceSet`, which extends `SynchronizedXTextResourceSet` and calls `getResource`, which in turn tries to create a new `XTextResource`, making the deadlock complete.

Quote from https://www.eclipse.org/forums/index.php?t=msg&th=899781&goto=1519740&

> EMF can safely be used in multi-threaded environments; however, EMF 
does not, itself, ensure thread-safety in application model 
implementations. Data structures are unsynchronized, for performance and 
to avoid potential deadlock situations. The expectation is that a 
complete instance of the model (including resources and resource set, if 
present) should only be accessed by one thread at a time, and that the 
synchronization should be provided by the application at a higher level.

# Solution

Synchronise access to XText from the `XillProcessor`

**Comment by psievinen** [comment]
before fix:
<img width="1383" alt="before" src="https://user-images.githubusercontent.com/28049768/39805237-910b910a-5376-11e8-9109-79b8d0321275.png">
after fix:
![after](https://user-images.githubusercontent.com/28049768/39805260-9b278e64-5376-11e8-866b-a7ff4a84ee38.png)
